version: "3.8"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:postgres100@db:5432/urlshortener
      REDIS_URL: redis://redis:6379/0

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres100
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"