## first stage build

FROM python:3.12-slim AS build

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src /app/

## stage2 multi stage build.

FROM python:3.12-slim AS stage

WORKDIR /app

COPY --from=build /app /app

## running on a non root user

USER 1001

EXPOSE 8080

CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]

