FROM python:3.12-slim AS build

WORKDIR /app

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"  
##env used ti create an easy file path for the dependencies so i can copy them in the second stage build

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src /app/src


##stage 2 build

FROM python:3.12-slim

WORKDIR /app

COPY --from=build /opt/venv /opt/venv
COPY --from=build /app /app

ENV PATH="/opt/venv/bin:$PATH"

USER 1001

EXPOSE 8080

CMD ["python", "-m", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080"]