## first stage build

FROM python:3.12-slim AS build

WORKDIR /app

RUN pip install --no-cache-dir -r requirements.txt

COPY requirements.txt .

COPY src /app/

## stage2 multi stage build.

FROM python:3.12-slim AS stage

WORKDIR /app

COPY --from=build /app /src 

USER 1001:1001

EXPOSE 8080

CMD ["python, main.py"]

