name: Build, Push and Deploy

on:
  push: 
    branches: [ 'main ']
    paths:
      - app/** ##this means when the app code changes it will trigger not when you run tf apply or update workflows
      
permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECR_REPO: ${{ vars.ECR_REPO }}

jobs:
  build-push-deploy:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.confirm == 'BUILD' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $REGISTRY/$ECR_REPO:${{ github.sha }} ./app
          echo "image=$REGISTRY/$ECR_REPO:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ steps.build-image.outputs.image }}
          format: 'table'
          exit-code: 1 ## so this fails the pipeline, so it doesn't push a bad image
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true

      - name: Push image
        run: |
          docker push ${{ steps.build-image.outputs.image }}
          docker tag ${{ steps.build-image.outputs.image }} $REGISTRY/$ECR_REPO:latest
          docker push $REGISTRY/$ECR_REPO:latest

      - name: Download task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition nur-ecs \
            --query taskDefinition > task-definition.json

      - name: Update task definition with new image
        id: update-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: nur-app
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy to ECS via CodeDeploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.update-task-def.outputs.task-definition }}
          service: ${{ vars.ECS_SERVICE_NAME }}
          cluster: ${{ vars.ECS_CLUSTER_NAME }}
          wait-for-service-stability: true
          codedeploy-appspec: .github/workflows/appspec.json
          codedeploy-application: app
          codedeploy-deployment-group: ${{ vars.DEPLOYMENT_GROUP_NAME }}

          ##this file is for updating the deployment - blue/green only.